# Generated by Django 5.0.1 on 2024-05-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_hub', '0007_remove_birthday_unique_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='user_id',
            new_name='user',
        ),
    ]
