# Generated by Django 5.0.1 on 2024-05-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_hub', '0008_rename_user_id_birthday_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='birthday',
            name='unique_birthday',
        ),
        migrations.AddConstraint(
            model_name='birthday',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'nickname', 'picture', 'user'), name='unique_birthday', violation_error_message='This person already exists.'),
        ),
    ]
