# Generated by Django 5.0.1 on 2024-06-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_hub', '0011_remove_birthday_unique_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='ignore_year',
            field=models.BooleanField(blank=True, default=False, verbose_name="I don't know the birth year"),
        ),
    ]
