# Generated by Django 5.0.1 on 2024-06-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_hub', '0012_birthday_ignore_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='last_name',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter notes about this person and their birthday.', max_length=250),
        ),
    ]
